### ISSUE TITLE
Compile from source ok, import error

### ISSUE THREAD

**Issue by yconst** [samjabrahams/tensorflow-on-raspberry-pi#133]
Hi, I'm compiling from source on a RPi 3 Stretch image. Compile completes without errors, wheel builds ok, pip installs but import fails.

### Hardware/Software Info

Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: 
* Operating System used: 
* Version of Python used: 
* SD card memory size: 
* Size of USB/other device used as swap (if building from source): 
* TensorFlow git commit hash (if building from source): 

Relevant Console Output/Logs:

**Comment by UICJohn** [comment]
I am facing the problem exactly your case.  Have you found the solution? Thanks!

**Comment by yconst** [comment]
No, I gave up after a while.

**Comment by zoken01** [comment]
I'm having the same issue..

```
>>>import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow9ConcatCPUINS_8bfloat16EEEvPNS_10DeviceBaseERKSt6vectorISt10unique_ptrINS_6TTypesIT_Li2EiE11ConstMatrixESt14default_deleteIS9_EESaISC_EEPNS8_6MatrixE

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

Any solutions?

**Comment by tlkh** [comment]
Same issue here. Previously succeeded. I suspect it's a problem with the newer versions of TensorFlow.

**Comment by klokik** [comment]
Same here:
OS: Archlinux Arm
Python: 3.6.4
TensorFlow: 1.6.0
Hardware: Samsung Arm chromebook (Exynos 5250)
Kernel: 4.15.9-1-ARCH
Oracle JDK 1.8.0_162

**Comment by tlkh** [comment]
The fix for me was just to compile TF r1.4. I have a fully working TF.

**Comment by iyanmv** [comment]
Same here... :(

After 7 hours compiling (and several failed tries before) it cannot import the module.
OS: Raspbian Stretch
Python: 3.5.3
TensorFlow: 1.6.0
Hardware: Raspberry Pi 3

I used **gcc 4.8.5** and **bazel 0.10.1** to generate the .whl package. I tried TF 1.7.0 with bazel 0.10.1 and 0.12.0 but it failed to compile. I will try wtih TF 1.4.

**Comment by iyanmv** [comment]
> The fix for me was just to compile TF r1.4. I have a fully working TF.
@tlkh Can you share what versions of gcc and bazel you used to compile TF r1.4. Thanks!

**Comment by tlkh** [comment]
@iyanmv I’m so sorry, I don’t actually remember. But there was an additional flag I had to set, I think it was some legacy thing.

**Comment by zhewang95** [comment]
Put libtensorflow_framework.so in LD_LIBRARY_PATH can solve this problem.
