### ISSUE TITLE
Import error after compiling from source

### ISSUE THREAD

**Issue by c13arm** [samjabrahams/tensorflow-on-raspberry-pi#135]
### Describe the Issue
After installing Tensorflow from source I try to import it by typing: "python3" and then "import tensorflow as tf" which results in an error.

### Steps to Reproduce
Followed the step-by-step guide by building from source. In the configure file I changed to python3 and library path 3.4.

### Hardware/Software Info

* Raspberry Pi model: Pi 2 Model B v1.1
* Operating System used: Raspian GNU/Linux version 8 (jessie)
* Version of Python used: 3.4.2
* SD card memory size: 16GB
* Size of USB/other device used as swap (if building from source): 16GB
* TensorFlow git commit hash (if building from source): 56422034fe039d7e8a57392957ed0c8b4b4efe56

### Relevant Console Output/Logs
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: /usr/local/lib/python3.4/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow9ConcatCPUINS_8bfloat16EEEvPNS_10DeviceBaseERKSt6vectorISt10unique_ptrINS_6TTypesIT_Li2EiE11ConstMatrixESt14default_deleteIS9_EESaISC_EEPNS8_6MatrixE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: /usr/local/lib/python3.4/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow9ConcatCPUINS_8bfloat16EEEvPNS_10DeviceBaseERKSt6vectorISt10unique_ptrINS_6TTypesIT_Li2EiE11ConstMatrixESt14default_deleteIS9_EESaISC_EEPNS8_6MatrixE

**Comment by tlkh** [comment]
#133 same issue

**Comment by zoken01** [comment]
Same here.

**Comment by tlkh** [comment]
The fix for me was to compile TF r1.4 instead. It’s working perfectly fine.

**Comment by zoken01** [comment]
> The fix for me was to compile TF r1.4 instead. It’s working perfectly fine.

How do you do that?

**Comment by krejciadam** [comment]
The same problem here (RPi 3 with Ubuntu MATE). Happens with both tensorflow 1.7 and 1.6 for both Python 2.7 and 3.5. I'll keep trying with lower versions of TF - 1.5 and 1.4.

**Comment by zhewang95** [comment]
Seems like try different python version and tensorflow version can solve this problem. I have cross-compiled tensorflow1.9 for hi3536 with python3.5.3 while python3.4 and python3.6 both failed.

**Comment by zhewang95** [comment]
I found that put libtensorflow_framework.so in your LD_LIBRARY_PATH can solve this problem.

**Comment by tianyufang1958** [comment]
> I found that put libtensorflow_framework.so in your LD_LIBRARY_PATH can solve this problem.

Hello, I tried the same but no luck
