### ISSUE TITLE
Tensorflow and Raspberry Pi Error: Building from Source

### ISSUE THREAD

**Issue by yashn35** [samjabrahams/tensorflow-on-raspberry-pi#143]
I am trying to run a command to install Tensorflow from source, I use Bazel to install from source (This is being done a raspberry pi -- Linux OS software).

I followed the necessary steps of building from source (IMPORTANT Detail: I have to Bazel version 0.10.0 because it says that is the only version that is compatible for Tensorflowflow) So then, this what I am trying to do on my raspberry pi:

 

`./configure`

` bazel build -c opt --copt="-mfpu=neon-vfpv4" --copt="-funsafe-math-optimizations" --copt="-ftree-vectorize" --copt="-fomit-frame-pointer" --local_resources 1024,1.0,1.0 --verbose_failures tensorflow/tools/pip_package:build_pip_package
`

I get the following error when I run it (This is a super long installation and it was almost done installing all the files and then it suddenly said the build failed, and bazel couldn't be built. Does anyone know how to fix or have resources on how to fix this error)?

Here is the error message that I get:

   `collect2: error: ld returned 1 exit status
   Target //tensorflow/tools/pip_package:build_pip_package failed to build`

I would appreciate help as soon as someone gets a chance!

**Comment by benax-rw** [comment]
Facing the similar issue when I run ./configure  I get two errors as below:

ERROR: /home/pi/tf/tensorflow/third_party/toolchains/clang6/repo.bzl:25:19: Traceback (most recent call last):
	File "/home/pi/tf/tensorflow/third_party/toolchains/clang6/repo.bzl", line 22
		repository_rule(implementation = _clang6_configu..., ...')))})
	File "/home/pi/tf/tensorflow/third_party/toolchains/clang6/repo.bzl", line 25, in repository_rule
		attr.label(default = str(Label('//third_par...')))
expected Label or Label-returning function or NoneType for 'default' while calling label but got string instead: //third_party/toolchains/clang6:clang.BUILD.
ERROR: error loading package '': Extension file 'third_party/toolchains/clang6/repo.bzl' has errors.
