### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by SuperJonotron** [samjabrahams/tensorflow-on-raspberry-pi#33]
This may end up being be more of a question/discussion about the pi's limitations more so than a bug report but when running the Deep MNIST for Experts example (https://www.tensorflow.org/versions/r0.9/tutorials/mnist/pros/index.html) the pi3 runs out of resources during the evaluation step.  I searched quite a bit looking for a solution to this and have found people say something to the effect of "use batches to evaluate" but that's about as much info as anybody says about the topic.  

So is there a way to evaluate in batches instead of the example that does it all at once:

`print("test accuracy %g"%accuracy.eval(feed_dict={
    x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0}))`

I have not been able to find this process defined anywhere and will likely need to implement this in pi applications due to it's limited resources on processing large data sets.

running on a Pi3 on Raspbian GNU/Linux 8 (jessie)" with Python version 2.7.9

Full Console error:

Traceback (most recent call last):
  File "/home/pi/tensorflow/Tutorial2.py", line 114, in <module>
    x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0}))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 556, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3637, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
ResourceExhaustedError: OOM when allocating tensor with shape[10000,28,28,32]
     [[Node: Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape, Variable_2/read)]]
Caused by op u'Conv2D', defined at:
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/idlelib/run.py", line 116, in main
    ret = method(_args, *_kwargs)
  File "/usr/lib/python2.7/idlelib/run.py", line 324, in runcode
    exec code in self.locals
  File "/home/pi/tensorflow/Tutorial2.py", line 74, in <module>
    h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)
  File "/home/pi/tensorflow/Tutorial2.py", line 64, in conv2d
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 394, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2298, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1232, in __init__
    self._traceback = _extract_stack()

**Comment by samjabrahams** [comment]
I'll try to give a more comprehensive answer by the end of the weekend, but yes, you should be able to evaluate your graph in batches. Basically, instead of passing in the entire set of 10000 images, you should take subsets of it at a time and keep a running tally of the statistics you are interested in. For accuracy, you would want a running total of the "correct" guesses, and then you can take a floating point division of `num_correct / total_test_samples`. 

In real use, it's probably best to do the model training and evaluation on a more powerful rig than the RPi. It's a fun exercise to figure out how to run these examples on the RPi, but it's hardware is better suited for taking in pre-trained models. I'm sure it could learn smaller traditional models, though!

**Comment by SuperJonotron** [comment]
I look forward to the more detailed answer.  I would love to see how one would go about breaking up the mnist test data into batches and/or a more general approach for a data set and load that into the evalutation. 

I agree with the sentiment of training and evaluating on a more powerful system but at the moment my pi is the only thing I have that can run tensorflow so i'm trying to see what I can and can't get away with.  I also like the idea of doing large scale training evaluating on a "base" model elsewhere and then possibly collecting more data on the pi and teaching/evaluating it in runtime and then rejecting or keeping the new model based on the results.  Just gotta find it's limitations first.

**Comment by samjabrahams** [comment]
Hey @SuperJonotron - sorry for the extra late reply; this month has been nutty.

Here's a simple example from a workshop I gave last week- check out the section titled "Validate" toward the bottom of the notebook:

https://github.com/samjabrahams/tensorflow-workshop/blob/master/AlexNet%20Transfer%20Learning.ipynb

Basically, it takes batches of the validation data and increments a counter for how many it got correct in that batch. At the end, you do a floating point division of the `num_correct / total`
