### ISSUE TITLE
Issues about Tensorflow on New BubbleGum 96 ARM64 board

### ISSUE THREAD

**Issue by alephman** [samjabrahams/tensorflow-on-raspberry-pi#35]
### Describe the Issue

1) 
I want to port tensorflow to a new arm64 board(https://www.96boards.org/products/ce/bubblegum96/), following your guide:

**project# pip2 install tensorflow-0.9.0rc0-cp27-none-linux_armv7**
tensorflow-0.9.0rc0-cp27-none-linux_armv7l.whl is not a supported wheel on this platform.
Storing debug log for failure in /root/.pip/pip.log

**project# pip3 install tensorflow-0.9.0-py3-none-any.whl** 
Unpacking ./tensorflow-0.9.0-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.2 in /usr/local/lib/python3.4/dist-packages (fr)
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0b2 in /usr/local/lib/python3.4/dist-package)
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /usr/local/lib/python3.4/dist-packages (fro)
Requirement already satisfied (use --upgrade to upgrade): wheel>=0.26 in /usr/local/lib/python3.4/dist-packages (fro)
Installing collected packages: tensorflow
Successfully installed tensorflow
Cleaning up...

## I am wondering why  the tensorflow-0.9.0rc0-cp27-none-linux_armv7 file can't be installed on my arm64 board?  What's the difference between tensorflow-0.9.0rc0-cp27-none-linux_armv7.whl and tensorflow-0.9.0-py3-none-any.whl ?

2) After installing the tensorflow-0.9.0-py3-none-any.whl, I was trying to do a test:

root@linaro-alip:/project# python3
Python 3.4.2 (default, Oct  8 2014, 12:59:09) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helpr
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: /usr/local/lib/python3.4/dist-packages/tensorflow/python/_pywrap_tensorflow.so: wrong ELF class: ELFCLA2
>> 

It seems the tensorflow doesn't be imported successfully.

**Comment by samjabrahams** [comment]
Hi @alephman,

Thanks for opening this up! Those Python wheel files were built for Raspbian 8.0 on Raspberry Pi 3, so the binaries may not work exactly.

Have you tried [installing from sources](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md)? It's possible that you may be able to build TensorFlow for your system, though I haven't tried it on the Bubblegum-96 board.

**Comment by alephman** [comment]
Hi, 
following your guide, I am trying to do it step by step, but get stuck with this:

root@linaro-alip:~/bazel# ./compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.Unrecognized option: -client
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Building output/bazel

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
I tried many different values with  " -J-Xmx800M"/ " -J-Xmx500M"/ " -J-Xmx350M"  flag in scripts/bootstrap/compile.sh,  the same output there.

When I try with  " -J-Xmx250M",  a difference output like this:

The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.sun.tools.javac.comp.Resolve.findMethodInScope(Resolve.java:1626)
	at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1719)
	at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1671)
	at com.sun.tools.javac.comp.Resolve$9.doLookup(Resolve.java:2424)
	at com.sun.tools.javac.comp.Resolve$BasicLookupHelper.lookup(Resolve.java:3083)
	at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3334)
	at com.sun.tools.javac.comp.Resolve.resolveQualifiedMethod(Resolve.java:2421)
	at com.sun.tools.javac.comp.Resolve.resolveQualifiedMethod(Resolve.java:2415)
	at com.sun.tools.javac.comp.Resolve.resolveQualifiedMethod(Resolve.java:2410)
	at com.sun.tools.javac.comp.Annotate.enterAnnotation(Annotate.java:301)
	at com.sun.tools.javac.comp.Annotate.enterAnnotation(Annotate.java:236)
	at com.sun.tools.javac.comp.MemberEnter.actualEnterAnnotations(MemberEnter.java:923)
	at com.sun.tools.javac.comp.MemberEnter.access$600(MemberEnter.java:64)
	at com.sun.tools.javac.comp.MemberEnter$5.run(MemberEnter.java:876)
	at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:143)
	at com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:129)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:512)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.enterTrees(JavacProcessingEnvironment.java:1015)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.<init>(JavacProcessingEnvironment.java:902)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.next(JavacProcessingEnvironment.java:921)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1187)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.main.Main.compile(Main.java:381)
	at com.sun.tools.javac.main.Main.compile(Main.java:370)
	at com.sun.tools.javac.main.Main.compile(Main.java:361)
	at com.sun.tools.javac.Main.compile(Main.java:56)
	at com.sun.tools.javac.Main.main(Main.java:42)

Compiling Bazel Java code...

1) Is there any way to debug this problem?
2) I want to build newer tensorflow(r0.9,r0.10 ) source code for deploying distribution tensorflow in a cluster of boards ,  do I need to checkout the latest protobuf/bazel code  or just checkout the version you listed in guide?

Thanks!

**Comment by samjabrahams** [comment]
Hi @alephman - sorry for the delayed response; this month has been a bit nutty. 

1. What happens if you remove the `-J-Xmx###M` flag entirely?
2. You should be able to make do with the version I listed in the guide. When new releases of TensorFlow come out, I update the guide to make sure everything still works together (I'm waiting for the official 0.10 release instead of the current release candidate)

**Comment by alephman** [comment]
Thanks Sam.  Finally it works now. Thanks again for your guide!

**Comment by samjabrahams** [comment]
Awesome! Glad that it worked out for you- apologies once again for the delayed response. Closing this baby up.

**Comment by ipiazza** [comment]
Hi,
I am also facing similar issues by trying to compile from source Tensorflow for PINE64.
Specifically I am getting the same GC error previously seen while compiling bazel.
Here below the error:
bazel-0.12.0:$ ./compile.sh &
The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.sun.tools.javac.comp.Annotate.enterAnnotation(Annotate.java:328)
	at com.sun.tools.javac.comp.Annotate.enterAnnotation(Annotate.java:236)
	at com.sun.tools.javac.comp.MemberEnter.actualEnterAnnotations(MemberEnter.java:923)
	at com.sun.tools.javac.comp.MemberEnter.access$600(MemberEnter.java:64)
	at com.sun.tools.javac.comp.MemberEnter$5.run(MemberEnter.java:876)
	at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:143)
	at com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:129)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:512)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
	at com.sun.tools.javac.main.JavaCompiler.enterTreesIfNeeded(JavaCompiler.java:965)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1242)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.main.Main.compile(Main.java:381)
	at com.sun.tools.javac.main.Main.compile(Main.java:370)
	at com.sun.tools.javac.main.Main.compile(Main.java:361)
	at com.sun.tools.javac.Main.compile(Main.java:56)
	at com.sun.tools.javac.Main.main(Main.java:42)

[1]+  Done                    ./compile.sh

Any chance you can help out solving it?
