### ISSUE TITLE
Tensorflow bazel build error

### ISSUE THREAD

**Issue by AaronSeah** [samjabrahams/tensorflow-on-raspberry-pi#85]
### Describe the Issue
After bazel installation, I proceeded to configure Tensorflow and build. Error occurs when building Tensorflow. I am new to Raspberry Pi as I just bought it to do a project, any help would be greatly appreciated.

```
Target //src:bazel up-to-date:
  bazel-bin/src/bazel
INFO: Elapsed time: 19448.170s, Critical Path: 18836.57s
WARNING: /tmp/bazel_7kFiSyEp/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_7kFiSyEp/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.

Build successful! Binary is here: /home/pi/tf/bazel/output/bazel
pi@gene:~/tf/bazel $ cd . .
pi@gene:~/tf/bazel $ cd ..
pi@gene:~/tf $ cd bazel
pi@gene:~/tf/bazel $ sudo cp output/bazel /usr/local/bin/bazel
pi@gene:~/tf/bazel $ bazel
Extracting Bazel installation...
..............................................................................................................................................................................................................................................................
                                               [bazel release 0.4.3- (@non-git)]
Usage: bazel <command> <options> ...

Available commands:
  analyze-profile     Analyzes build profile data.
  build               Builds the specified targets.
  canonicalize-flags  Canonicalizes a list of bazel options.
  clean               Removes output files and optionally stops the server.
  coverage            Generates code coverage report for specified test targets.
  dump                Dumps the internal state of the bazel server process.
  fetch               Fetches external repositories that are prerequisites to the targets.
  help                Prints help for commands, or the index.
  info                Displays runtime info about the bazel server.
  mobile-install      Installs targets to mobile devices.
  query               Executes a dependency graph query.
  run                 Runs the specified target.
  shutdown            Stops the bazel server.
  test                Builds and runs the specified test targets.
  version             Prints version information for bazel.

Getting more help:
  bazel help <command>
                   Prints help and options for <command>.
  bazel help startup_options
                   Options for the JVM hosting bazel.
  bazel help target-syntax
                   Explains the syntax for specifying targets.
  bazel help info-keys
                   Displays a list of keys used by the info command.
pi@gene:~/tf/bazel $ cd ..

pi@gene:~/tf $ git clone --recurse-submodules https://github.com/tensorflow/tensorflow
Cloning into 'tensorflow'...
remote: Counting objects: 170252, done.
remote: Total 170252 (delta 0), reused 0 (delta 0), pack-reused 170251
Receiving objects: 100% (170252/170252), 91.34 MiB | 1.42 MiB/s, done.
Resolving deltas: 100% (130884/130884), done.
Checking connectivity... done.
Checking out files: 100% (5894/5894), done.
pi@gene:~/tf $ cd tensorflow
pi@gene:~/tf/tensorflow $ grep -Rl 'lib64' | xargs sed -i 's/lib64/lib/g'
pi@gene:~/tf/tensorflow $ sudo nano tensorflow/core/platform/platform.h
pi@gene:~/tf/tensorflow $ sudo nano WORKSPACE

pi@gene:~/tf/tensorflow $ ./configure
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
Do you wish to use jemalloc as the malloc implementation? [Y/n]
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N]
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N]
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.4/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]
/usr/local/lib/python3.4/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N]
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N]
No CUDA support will be enabled for TensorFlow
.............................................................................................................................................................................................................................................................
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
Configuration finished

pi@gene:~/tf/tensorflow $ bazel build -c opt --copt="-mfpu=neon-vfpv4" --copt="-funsafe-math-optimizations" --copt="-ftree-vectorize" --copt="-fomit-frame-pointer" --local_resources 1024,1.0,1.0 --verbose_failures tensorflow/tools/pip_package:build_pip_package
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /home/pi/tf/tensorflow/third_party/gpus/cuda_configure.bzl:883:18: unexpected keyword 'environ' in call to repository_rule(implementation: function, *, attrs: dict or NoneType = None, local: bool = False).
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'third_party/gpus/cuda_configure.bzl' has errors.
INFO: Elapsed time: 42.211s
pi@gene:~/tf/tensorflow $
```

### Steps to Reproduce
Followed step by step installation by source

### Hardware/Software Info

Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: Raspberry Pi 3 Model B
* Operating System used: Raspian (jessie 8.0) - NOOBs installation
* Version of Python used: 3.4
* SD card memory size: 64gb
* Size of USB/other device used as swap (if building from source): 8gb
* TensorFlow git commit hash (if building from source): 

### Relevant Console Output/Logs
[error tensorflow.txt](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/files/892106/error.tensorflow.txt)

**Comment by samjabrahams** [comment]
Thanks for opening this up @AaronSeah. This is most likely due to needing to upgrade from Bazel 0.4.3 to 0.4.5. Unfortunately, that means you're going to have to rebuild bazel, replacing the wget command to point to https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel-0.4.5-dist.zip. Sorry that you'll have to take the time to go through the bazel compilation process again :/

I'm in the middle of compiling TensorFlow 1.0.1 for Python 2.7 and 3.4, and the updated instructions will be available once I've confirmed they work verbatim.

**Comment by AaronSeah** [comment]
Hi @samjabrahams , no worries about spending time compiling bazel again. Thanks for your help! I'll update you if it works.

**Comment by AaronSeah** [comment]
Hi @samjabrahams , I've updated to Bazel 0.4.5 and tried running Tensorflow. This was the build error I got.

Just so you know, I am using my laptop to SSH to my Pi to do the configurations. Afterward I ran `./configure` I closed my SSH and remoted into the Pi to run the **Tensorflow build command**. This error occurs afterwards. 

Do I have to rebuild the entire steps on one sitting on the same SSH window?

Appreciate any help, thanks!

```
pi@gene:~/tf/bazel` $ bazel
...................................................................................................................................................................................................................................................................................
                                               [bazel release 0.4.5- (@non-git)]
Usage: bazel <command> <options> ...

Available commands:
  analyze-profile     Analyzes build profile data.
  build               Builds the specified targets.
  canonicalize-flags  Canonicalizes a list of bazel options.
  clean               Removes output files and optionally stops the server.
  coverage            Generates code coverage report for specified test targets.
  dump                Dumps the internal state of the bazel server process.
  fetch               Fetches external repositories that are prerequisites to the targets.
  help                Prints help for commands, or the index.
  info                Displays runtime info about the bazel server.
  mobile-install      Installs targets to mobile devices.
  query               Executes a dependency graph query.
  run                 Runs the specified target.
  shutdown            Stops the bazel server.
  test                Builds and runs the specified test targets.
  version             Prints version information for bazel.

Getting more help:
  bazel help <command>
                   Prints help and options for <command>.
  bazel help startup_options
                   Options for the JVM hosting bazel.
  bazel help target-syntax
                   Explains the syntax for specifying targets.
  bazel help info-keys
                   Displays a list of keys used by the info command.
pi@gene:~/tf/bazel $ cd ..
pi@gene:~/tf $ cd tensorflow
pi@gene:~/tf/tensorflow $ ./configure
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
Do you wish to use jemalloc as the malloc implementation? [Y/n]
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N]
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N]
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.4/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]
/usr/local/lib/python3.4/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N]
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N]
No CUDA support will be enabled for TensorFlow
...................................................................................................................................................................................................................................................................
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Configuration finished
pi@gene:~/tf/tensorflow $ bazel build -c opt --copt="-mfpu=neon-vfpv4" --copt="-funsafe-math-optimizations" --copt="-ftree-vectorize" --copt="-fomit-frame-pointer" --local_resources 1024,1.0,1.0 --verbose_failures tensorflow/tools/pip_package:build_pip_package
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /home/pi/tf/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/pi/tf/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
ERROR: /home/pi/tf/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@plottable//': Error downloading [https://github.com/palantir/plottable/archive/v1.16.1.tar.gz] to /home/pi/.cache/bazel/_bazel_pi/4770c5ca1786316d370c900c0b614a6d/external/plottable/v1.16.1.tar.gz: SSL peer shut down incorrectly and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 1782.179s
pi@gene:~/tf/tensorflow $

```

[bazel 045 TF build error.txt](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/files/895209/bazel.045.TF.build.error.txt)

**Comment by AaronSeah** [comment]
@samjabrahams thanks! i managed to compile and build tensorflow. After installing wheel and running pip to install I encountered this error. Is it because the files are not downloaded? Please advice, thank you! 

```
INFO: From Compiling tensorflow/python/pywrap_tensorflow_internal.cc:
bazel-out/local-py3-opt/bin/tensorflow/python/pywrap_tensorflow_internal.cc: In function 'PyObject* _wrap_PyRecordReader_New(PyObject*, PyObject*)':
bazel-out/local-py3-opt/bin/tensorflow/python/pywrap_tensorflow_internal.cc:4784:138: warning: 'arg2' may be used uninitialized in this function [-Wmaybe-uninitialized]
     result = (tensorflow::io::PyRecordReader *)tensorflow::io::PyRecordReader::New((string const &)*arg1,arg2,(string const &)*arg3,arg4);
                                                                                                                                          ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-self-assign" [enabled by default]
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 30502.622s, Critical Path: 28984.97s

pi@gene:~/tf/tensorflow $ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Wed 5 Apr 16:08:32 UTC 2017 : === Using tmpdir: /tmp/tmp.NdaD9yW9Hx
~/tf/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles ~/tf/tensorflow
~/tf/tensorflow
/tmp/tmp.NdaD9yW9Hx ~/tf/tensorflow
Wed 5 Apr 16:08:44 UTC 2017 : === Building wheel
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
~/tf/tensorflow
Wed 5 Apr 16:10:16 UTC 2017 : === Output wheel file is in: /tmp/tensorflow_pkg

pi@gene:~/tf/tensorflow $ sudo pip install /tmp/tensorflow_pkg/tensorflow-1.0.0-cp27-none-linux_armv7l.whl
Requirement '/tmp/tensorflow_pkg/tensorflow-1.0.0-cp27-none-linux_armv7l.whl' looks like a filename, but the file does not exist
Unpacking /tmp/tensorflow_pkg/tensorflow-1.0.0-cp27-none-linux_armv7l.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1365, in unpack_url
    unpack_file_url(link, location, download_dir)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 640, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 640, in unpack_file
    unzip_file(filename, location, flatten=not filename.endswith(('.pybundle', '.whl')))
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 508, in unzip_file
    zipfp = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/tmp/tensorflow_pkg/tensorflow-1.0.0-cp27-none-linux_armv7l.whl'

Storing debug log for failure in /root/.pip/pip.log

``


[after tensorflow .txt](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/files/901361/after.tensorflow.txt)

**Comment by samjabrahams** [comment]
Are you building from master? The binary probably won't use "1.0.0" but either 1.0.1, 1.1.0-rc0, or 1.1.0-rc1. Try either tab-completing the `pip install /tmp/tensorflow_pkg/` command or find out the actual name of the file by typing `ls /tmp/tensorflow_pkg`.

**Comment by samjabrahams** [comment]
To be a bit more specific, the file might not be called:

```
/tmp/tensorflow_pkg/tensorflow-1.0.0-cp27-none-linux_armv7l.whl
```

But rather something like

```
/tmp/tensorflow_pkg/tensorflow-1.0.1-cp27-none-linux_armv7l.whl
OR
/tmp/tensorflow_pkg/tensorflow-1.1.0-rc0-cp27-none-linux_armv7l.whl
```

Or something else, depending on the version you built.

**Comment by AaronSeah** [comment]
Hi @samjabrahams I tried rebuilding and I got this error after trying to install the wheel. I've been trying to build from master.

```
INFO: Elapsed time: 30668.187s, Critical Path: 26191.91s

pi@gene:~/tf/tensorflow $ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

Sun 9 Apr 02:24:48 UTC 2017 : === Using tmpdir: /tmp/tmp.Ezw9k8MnDa
~/tf/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles ~/tf/tensorflow
~/tf/tensorflow
/tmp/tmp.Ezw9k8MnDa ~/tf/tensorflow
Sun 9 Apr 02:25:00 UTC 2017 : === Building wheel
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
~/tf/tensorflow

Sun 9 Apr 02:26:32 UTC 2017 : === Output wheel file is in: /tmp/tensorflow_pkg
pi@gene:~/tf/tensorflow $ pip install --user /tmp/tensorflow_pkg/tensorflow-1.1.0rc1-cp34-cp34m-linux_armv7l.whl

tensorflow-1.1.0rc1-cp34-cp34m-linux_armv7l.whl is not a supported wheel on this platform.
Storing debug log for failure in /home/pi/.pip/pip.log

```

**Comment by samjabrahams** [comment]
Try:

```
sudo pip3 install /tmp/tensorflow_pkg/tensorflow-1.1.0rc1-cp34-cp34m-linux_armv7l.whl
```

[README link](https://github.com/samjabrahams/tensorflow-on-raspberry-pi#tensorflow-101-cp27-none-linux_armv7lwhl-is-not-a-supported-wheel-on-this-platform)

**Comment by AaronSeah** [comment]
Oh, silly mistake. I forgot I installed Python 3.4, thanks!

**Comment by SreehariRamMohan** [comment]
I am getting the same error as you were
```
 sudo pip3 install /tmp/tensorflow_pkg/tensorflow-1.1.0-cp27-none-linux_armv7l.whl
Requirement '/tmp/tensorflow_pkg/tensorflow-1.1.0-cp27-none-linux_armv7l.whl' looks like a filename, but the file does not exist
tensorflow-1.1.0-cp27-none-linux_armv7l.whl is not a supported wheel on this platform.
```
Can you explain how you fixed this. Thanks! Any help would be greatly appreciated!
