### ISSUE TITLE
Compiled whl for Python 3.5.2 and TF1.0.1

### ISSUE THREAD

**Issue by RedDeathAt614** [samjabrahams/tensorflow-on-raspberry-pi#92]
### Describe the Issue
Hey! 

Thanks for providing this awesome guide! 

I successfully compiled TF1.0.1 for Python 3.5.2 on a Pi 3. Would be happy to share the whl if anybody's interested. Just let me know.

### Steps to Reproduce
Pretty much followed the steps except:

1.  I used Bazel 0.4.5 instead of 0.4.3 (which now have been updated I see)
2. During `./configure` I had a problem with downloading plottable from https://github.com/palantir/plottable/archive/v1.16.1.tar.gz even though the link is working perfectly fine. I grabbed it from there and uploaded it to a Google Cloud Storage bucket, made it public and added the link to the WORKSPACE file in the TF repo on line 462 so that part looks like:
```new_http_archive(
  name = "plottable",
  build_file = "bower.BUILD",
  url = "https://storage.googleapis.com/hyvi-data-eu/v1.16.1.tar.gz",
  strip_prefix = "plottable-1.16.1",
)```

### Hardware/Software Info

Please provide the following information about your Raspberry Pi setup:

* Raspberry Pi model: 3-B
* Operating System used: Raspbian
* Version of Python used: 3.5.2
* SD card memory size: 16GB
* Size of USB/other device used as swap (if building from source): 16GB
* TensorFlow git commit hash (if building from source): From tag v1.0.1

### Relevant Console Output/Logs
Only tested this yet with the "hello world" example.

**Comment by fevemania** [comment]
Congratulation!

I have compile for bazel for five times, but it still not work successfully.

Would you mind share your .whl file with me?
I would like to try it on my Rpi 3-B !

I'm using python 3.5.3, will that impact the result?

**Comment by RedDeathAt614** [comment]
Of course @fevemania - grab it from here: https://www.dropbox.com/s/gy4kockdbdyx85j/tensorflow-1.0.1-cp35-cp35m-linux_armv7l.whl?dl=1

Not sure what the impact of using Python 3.5.3 would be though. Let me know if it works for you!

**Comment by fevemania** [comment]
@RedDeathAt614 , this is fantastic! Within 5 minute, tensorflow was installed and work fine.
<img width="583" alt="2017-04-14 15 39 13" src="https://cloud.githubusercontent.com/assets/16337667/25036966/2ca3ad72-2129-11e7-9c50-418c8f58e6ab.png">

**Comment by ebswift** [comment]
Nice work, I got this working too.  I'm a total newbie and had to start research from a blank slate so it did take a little longer than 5 minutes for me ;).  Thank you!

**Comment by weiseom** [comment]
Awesome! It works great on Ubuntu mate with Python 3.5 Thanks a lot! :)

**Comment by gasparka** [comment]
Used the wheel shared by @RedDeathAt614  for ODROID-XU4 image:
``ubuntu-16.04.3-4.9-mate-odroid-xu4-20170824.img``

Also installed Keras(latest,2.0.8), needed to install h5py and scipy via ``apt`` as pip3 install failed.
Everything works, thank you for sharing :)

**Comment by Nuruddinjr** [comment]
Works with me too, thanks man! @RedDeathAt614

**Comment by bwc88** [comment]
Thank you @RedDeathAt614. The wheel works fine for me as well. My platform is Python 3.5.3 + Keras 2.1.2 on Pi-2B. In addition, It's much faster (4x) than theano 1.0.1 backend I installed :)

**Comment by abhiramvenkata** [comment]
do you have whl for 1.2.1 tf for arm71 or 1.1.0tf is also fine ,if you do please share and python version is 3.5

**Comment by RedDeathAt614** [comment]
Nope I'm afraid not. We had to dump the Pi because it was too slow for our needs so I'm not actively working on TF and Pi's currently.

**Comment by ilgindogan** [comment]
@RedDeathAt614 I wanna install open cv and tensorflow in the same enviroment. But ı have with tensorflow version. I do not tensorflow 3.5 version. I saw the your dropbox link which is 14 April 2017 it seems that link expired. Please help to me with this matter . TF working with python 3.5 . 
Link below does not work anymore.
https://www.dropbox.com/s/gy4kockdbdyx85j/tensorflow-1.0.1-cp35-cp35m-linux_armv7l.whl?dl=1

**Comment by RedDeathAt614** [comment]
@ilgindogan sorry the dropbox link expired. Here's a new one if you still need it https://www.dropbox.com/s/gy4kockdbdyx85j/tensorflow-1.0.1-cp35-cp35m-linux_armv7l.whl?dl=0 (and sorry for late reply)

**Comment by RedDeathAt614** [comment]
@samjabrahams Do you want a more sustainable way to share this image feel free to just grab it and place it somewhere you want?

**Comment by CT83** [comment]
@RedDeathAt614 For the time being, I have uploaded it to my AWS S3. Feel free to use [it](https://s3.amazonaws.com/temp-storage-ct83/tensorflow-1.0.1-cp35-cp35m-linux_armv7l.whl).
`wget https://s3.amazonaws.com/temp-storage-ct83/tensorflow-1.0.1-cp35-cp35m-linux_armv7l.whl`

**Comment by fgerard** [comment]
Thanks aaaaaaaaAA lot!
It is working on my Raspberry pi 3 b+ with python 3.5.3:
(ENV3.5-TF1.1.0.1) pi@raspberrypi:~/Projects $ python
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import tensorflow as tf
>>> tf.__version__
'1.0.1'
>>> np.__version__
'1.12.1'
>>> import cv2
>>> cv2.__version__
'3.4.1'
SUPER HAPPY!!

**Comment by ilgindogan** [comment]
Thank u for helping to me I did very well project with opencv and
tensorflow face recognition I am so happy thank u very much for support
guys.

2018-05-30 4:37 GMT+03:00 Felipe Gerard <notifications@github.com>:

**Comment by sreevan** [comment]
Thank you @RedDeathAt614, it was really a great help. Tried the hard way of building from source but in vain after 30 hours of waiting. Something prompted me look for python 3.5 wheel and voila this link. Very grateful for that. I am able to proceed with my bot.

**Comment by srivatsankrishnan** [comment]
@RedDeathAt614 I tried this wheel file installation on Ubuntu Mate 16.04 on my ras pi 3. I am getting this error:
"tensorflow-1.0.1-cp35-cp35m-linux_armv7l.whl is not a supported wheel on this platfom"

@weiseom Did you do anything different?
-Sri

**Comment by RedDeathAt614** [comment]
@srivatsankrishnan Hmm I have not played with this image for a while. I did not compile it on Ubuntu Mate but Raspian. That's my best guess at a reason...

**Comment by sgriset** [comment]
Installation for my pi 3 does not work :- (

sudo pip3 install tensorflwo-1.0.1-cp35-linux_arm71.whl?dl
Invalid requirement: 'tensorflwo-1.0.1-cp35-linux_arm71.whl?dl'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pyparsing.py", line 1632, in parseString
    raise exc
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pyparsing.py", line 3183, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 37), (line:1, col:38)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_install.py", line 252, in from_line
    req = Requirement(req)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'?dl'"

**Comment by RedDeathAt614** [comment]
Try removing the ?dl from the file name (what the error says)

**Comment by CT83** [comment]
@sgriset Also `tensorflwo`?
